import DataStore from './context'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Unsplash Gallery</title>
      </head>
      <body suppressHydrationWarning>
        <DataStore>{children}</DataStore>
      </body>
    </html>
  )
}
